import { Graduated } from '../model/graduated';

export const GetAllGraduates: Graduated[] = [
  {
    id: '1',
    dni: 123487339,
    cellphone: 3113215520,
    first_name: 'Aldemar',
    second_name: '',
    last_name: 'Portilla',
    second_last_name: 'Castañeda',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-2.png',
  },
  {
    id: '2',
    dni: 65549283,
    cellphone: 3113215520,
    first_name: 'Fabian',
    second_name: 'Camilo',
    last_name: 'Merlano',
    second_last_name: 'Osorio',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-3.png',
  },
  {
    id: '3',
    dni: 1245533246,
    cellphone: 3113215520,
    first_name: 'Miguel',
    second_name: 'Mauricio',
    last_name: 'Rodriguez',
    second_last_name: 'Mancilla',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-4.png',
  },
  {
    id: '4',
    dni: 1245533453,
    cellphone: 3113215520,
    first_name: 'Ricardo',
    second_name: 'Alexander',
    last_name: 'Rodriguez',
    second_last_name: 'Quevedo',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-8.png',
  },
  {
    id: '4',
    dni: 12435533453,
    cellphone: 3113215520,
    first_name: 'Maria',
    second_name: 'Adelma',
    last_name: 'Feijoo',
    second_last_name: 'Hernandez',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-9.png',
  },
  {
    id: '5',
    dni: 132423332213,
    cellphone: 3113215520,
    first_name: 'Rodrigo',
    second_name: 'Eduardo',
    last_name: 'Perez',
    second_last_name: 'Hernandez',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-10.png',
  },
  {
    id: '6',
    dni: 23234454323,
    cellphone: 3113215520,
    first_name: 'Catalina',
    second_name: '',
    last_name: 'Ruiz',
    second_last_name: 'Rojas',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-11.png',
  },
  {
    id: '7',
    dni: 12435533453,
    cellphone: 3113215520,
    first_name: 'Tatiana',
    second_name: 'Jose',
    last_name: 'Gonzalez',
    second_last_name: 'Mora',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-12.png',
  },
  {
    id: '8',
    dni: 12435533453,
    cellphone: 3113215520,
    first_name: 'Berenice',
    second_name: 'Consuelo',
    last_name: 'Espinoza',
    second_last_name: 'Castro',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-13.png',
  },
  {
    id: '9',
    dni: 12435533453,
    cellphone: 3113215520,
    first_name: 'Camilo',
    second_name: 'jose',
    last_name: 'Feijoo',
    second_last_name: 'Hernandez',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-14.png',
  },
  {
    id: '10',
    dni: 12435533453,
    cellphone: 3113215520,
    first_name: 'Maria',
    second_name: 'Jose',
    last_name: 'Cardenas',
    second_last_name: 'Garavito',
    email: 'aldermar@cbcfhut.com',
    photo: 'Ellipse-15.png',
  },
];
